version: '3'

services:
    image-gallery-mysql:
        container_name: image-gallery-mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        volumes:
            - ./ops/mysql:/docker-entrypoint-initdb.d"
            - ./var/mysql:/var/lib/mysql

    image-gallery-nginx:
        container_name: image-gallery-nginx
        build:
            context: ./ops/nginx
            args:
                UID: $U_ID
        ports:
            - '8080:80'
        volumes:
            - ./www/html:/code
            - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links: [image-gallery-php]

    image-gallery-php:
        container_name: image-gallery-php
        build:
            context: ./ops/php-fpm
            args:
                UID: $U_ID
        image: rendimiento-php:latest
        volumes:
            - ./www/html:/code

    image-gallery-redis:
        container_name: image-gallery-redis
        image: redis:7.0.0
        ports:
            - '6379:6379'
        volumes:
            - ./ops/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./var/redis:/data
        command: redis-server /usr/local/etc/redis/redis.conf

    image-gallery-rabbitmq:
        container_name: image-gallery-rabbitmq
        image: rabbitmq:3.9.17-management
        environment:
            RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
            RABBITMQ_DEFAULT_USER: 'rabbitmq'
            RABBITMQ_DEFAULT_PASS: 'rabbitmq'
            RABBITMQ_DEFAULT_VHOST: '/'
        volumes:
            - ./var/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
        ports:
            - '15672:15672'
            - '5672:5672'

    image-gallery-elasticsearch:
        container_name: image-gallery-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
        user: root
        environment:
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'TAKE_FILE_OWNERSHIP=1'
        volumes:
            - ./var/elasticsearch/data:/usr/share/elasticsearch/data
            - ./ops/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - '9200:9200'

    image-gallery-kibana:
        container_name: image-gallery-kibana
        image: docker.elastic.co/kibana/kibana:7.16.0
        ports:
            - '5601:5601'
        environment:
            ELASTICSEARCH_HOSTS: 'http://image-gallery-elasticsearch:9200'
        depends_on:
            - image-gallery-elasticsearch
